### ISSUE TITLE
ember-cli-traceur no longer registered w/ NPM

### ISSUE THREAD

**Issue by jayphelps** [davidblurton/ember-cli-traceur#2]
Noticed that `ember-cli-traceur` is no longer registered with NPM.

e.g. https://www.npmjs.org/search?q=ember-cli-traceur or 

```bash
$ npm install --save-dev ember-cli-traceur
npm ERR! 404 404 Not Found: ember-cli-traceur
npm ERR! 404 
npm ERR! 404 'ember-cli-traceur' is not in the npm registry.
```

**Comment by aaronagray** [comment]
This is still not registered on NPM, but you can install the package with this command.

```bash
npm install --save-dev davidblurton/ember-cli-traceur
```

**Comment by davidblurton** [comment]
Sorry, module is now on npm 
https://www.npmjs.com/package/ember-cli-traceur

I've updated to the latest version of `broccoli-traceur` - let me know if you have any issues.
